PLANTS = (
    "peashooter",
    "sunflower",
    "cherrybomb",
    "wallnut",
    "potatomine",
    "snowpea",
    "chomper",
    "repeater",
    "puffshroom",
    "sunshroom",
    "fumeshroom",
    "gravebuster",
    "hypnoshroom",
    "scaredyshroom",
    "iceshroom",
    "doomshroom",
    "lilypad",
    "squash",
    "threepeater",
    "tanglekelp",
    "jalapeno",
    "spikeweed",
    "torchwood",
    "tallnut",
    "seashroom",
    "plantern",
    "cactus",
    "blover",
    "splitpea",
    "starfruit",
    "pumpkin",
    "magnetshroom",
    "cabbagepult",
    "pot",
    "kernelpult",
    "coffeebean",
    "garlic",
    "umbrella",
    "marigold",
    "melonpult",
    "gatlingpea",
    "twinsunflower",
    "gloomshroom",
    "cattail",
    "wintermelon",
    "goldmagnet",
    "spikerock",
    "cobcannon",
    "imitater",
)

def get_asset_classification(file_name: str) -> str:
    normalized_name = file_name.lower()
    if normalized_name.startswith(("zombie", "vstombstones")) or normalized_name.endswith(("zombie", "zombotany")):
        return "Zombies"
    if normalized_name.startswith(PLANTS):
        return "Plants"
    return "Others"
