[project]
name = "pvzrskintools"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inquirerpy>=0.3.4",
    "rich>=15.0.0",
    "spineatlas>=1.0.13",
    "unitypy>=1.25.0",
]

[dependency-groups]
dev = [
    "nuitka>=4.1.2",
    "pip-licenses>=5.5.5",
    "pylint>=4.0.5",
    "ruff>=0.15.15",
]
