name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src/PvZRSkinTools'

    steps:
      - uses: actions/checkout@v7
      
      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: Run lint
        run: ./lint.sh
