name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: 'src/PvZRSkinTools'
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: ./.github/actions/setup-python

      - name: "Set up Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install npm dependencies
        run: npm --prefix ./node-tools install

      - name: Run build
        shell: bash
        run: ./build.sh

      - name: Zip build output
        shell: pwsh
        run: |
          Compress-Archive -Path build/PvZRSkinTools/* -DestinationPath ${{ github.workspace }}/PvZRSkinTools-${{ github.ref_name }}.zip
 
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ github.workspace }}/PvZRSkinTools-${{ github.ref_name }}.zip
